(() => {
"use strict";
let state={players:[],games:[]}, view="dashboard", gameId=null, currentUser=null, gameFilter="upcoming";
let financeData={seasons:[],tickets:[],expenses:[]}, financeLoaded=false, financeLoading=false, financeSeasonId=null;
let playerFinanceData={seasons:[],tickets:[]};
let access={profile:null,permissions:{},members:[],rolePermissions:[]};
let actingAs=null;
const isPreview=()=>!!actingAs;
const effectivePermissions=()=>actingAs?(actingAs.role==="super_admin"?Object.fromEntries(PERMISSIONS.map(x=>[x[0],true])):Object.fromEntries((access.rolePermissions||[]).filter(x=>x.role===actingAs.role&&x.enabled).map(x=>[x.permission,true]))):access.permissions;
const sb=window.supabaseClient;
const ROLES=[["super_admin","Super Admin"],["admin","Admin"],["attendance","Attendance"],["finance","Finance"],["viewer","Viewer"]];
const PERMISSIONS=[
 ["dashboard.view","Dashboard"],["players.view","View players"],["players.manage","Manage players"],
 ["games.view","View games"],["games.manage","Manage games"],["attendance.view","View attendance"],
 ["attendance.manage","Manage attendance"],["payments.view","View payments"],["payments.manage","Manage payments"],
 ["access.manage","Manage access"]
];
const roleName=r=>(ROLES.find(x=>x[0]===r)||["",r])[1];
const can=p=>effectivePermissions()?.[p]===true;
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const player=id=>state.players.find(p=>p.id===id);
const game=()=>state.games.find(g=>g.id===gameId)||state.games[0]||{participants:[]};
const dateText=d=>new Date(d+"T12:00:00").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});
const badge=(t,c="slate")=>'<span class="badge badge-'+c+'">'+t+"</span>";
const ticketForPlayer=(playerId,date)=>{const season=playerFinanceData.seasons.find(s=>date>=s.starts_on&&date<=s.ends_on);return season?playerFinanceData.tickets.find(t=>t.season_id===season.id&&t.player_id===playerId):null;};
const isSeasonTicket=(playerId,date)=>!!ticketForPlayer(playerId,date);

function showFatal(m){document.getElementById("app").innerHTML='<section class="card error-card"><h2>Football could not start</h2><p>'+esc(m)+'</p></section>';}
function accessDenied(){const e=currentUser?.email||"";document.getElementById("app").innerHTML='<section class="auth-card card access-denied"><div class="ball-logo">🔒</div><div class="eyebrow">ACCESS CONTROLLED</div><h1>Access pending</h1><p class="muted">The Google account <b>'+esc(e)+'</b> is not on the admin list.</p><p class="muted">Ask a Super Admin to add this email under <b>Admin & Access</b>, then sign in again.</p><button id="denied-out" class="btn btn-secondary">Sign out</button></section>';document.getElementById("denied-out").onclick=async()=>{await sb.auth.signOut();location.reload();};}
async function loadAccess(){const c=await sb.rpc("claim_access_profile");if(c.error)throw c.error;const m=await sb.rpc("get_my_access");if(m.error)throw m.error;if(!m.data?.allowed){access={profile:null,permissions:{},members:[],rolePermissions:[]};return false;}access.profile=m.data.profile;access.permissions=m.data.permissions||{};if(access.profile.role==="super_admin"){const a=await sb.rpc("admin_list_access");if(a.error)throw a.error;const p=await sb.rpc("admin_list_permissions");if(p.error)throw p.error;access.members=a.data||[];access.rolePermissions=p.data||[];}return true;}
function nextGameDate(){return new Date().toISOString().slice(0,10);}
function makeSeasonGames(){const out=[],start=new Date("2026-09-04T12:00:00"),end=new Date("2027-08-31T12:00:00");for(let d=new Date(start);d<=end;d.setDate(d.getDate()+7)){const date=d.toISOString().slice(0,10),summer=[6,7].includes(d.getMonth());out.push({id:crypto.randomUUID(),date,startTime:summer?"20:00":"19:30",endTime:summer?"22:00":"21:30",time:summer?"20:00–22:00":"19:30–21:30",location:"Castellón",participants:[]});}return out;}
async function save(){if(!currentUser)return;const check=async(q,label)=>{if(q.error)throw new Error(label+": "+q.error.message);return q;};if(can("players.manage")){const rp=await check(await sb.from("players").select("id"),"Loading players");const ids=new Set(state.players.map(p=>p.id));if(state.players.length)await check(await sb.from("players").upsert(state.players.map(p=>({id:p.id,name:p.name,phone:p.phone||null,email:p.email||null}))),"Saving players");for(const p of rp.data||[])if(!ids.has(p.id))await check(await sb.from("players").delete().eq("id",p.id),"Deleting player");}if(can("games.manage")){const rg=await check(await sb.from("games").select("id"),"Loading games");const ids=new Set(state.games.map(g=>g.id));if(state.games.length)await check(await sb.from("games").upsert(state.games.map(g=>({id:g.id,game_date:g.date,start_time:g.startTime,end_time:g.endTime,location:g.location}))),"Saving games");for(const g of rg.data||[])if(!ids.has(g.id))await check(await sb.from("games").delete().eq("id",g.id),"Deleting game");}if(can("attendance.manage")){const rr=await check(await sb.from("game_players").select("id"),"Loading Game squad");const ids=new Set(),rows=[];state.games.forEach(g=>(g.participants||[]).forEach(x=>{if(!x.rowId)x.rowId=crypto.randomUUID();ids.add(x.rowId);rows.push({id:x.rowId,game_id:g.id,player_id:x.guest?null:x.playerId,guest_name:x.guest?x.name:null,playing:!!x.playing,attended:!!x.attended,paid:!!x.paid});}));if(rows.length)await check(await sb.from("game_players").upsert(rows),"Saving Game squad");for(const x of rr.data||[])if(!ids.has(x.id))await check(await sb.from("game_players").delete().eq("id",x.id),"Deleting Game squad record");}if(can("payments.manage")){await check(await sb.from("payments").delete().neq("id","00000000-0000-0000-0000-000000000000"),"Resetting payments");const ps=[];state.games.forEach(g=>(g.participants||[]).forEach(x=>{if(!x.guest&&x.attended&&x.paid)ps.push({id:crypto.randomUUID(),player_id:x.playerId,game_id:g.id,payment_type:"game",paid:true});}));if(ps.length)await check(await sb.from("payments").insert(ps),"Saving payments");}}
async function loadRemote(options={}){const preserveGameId=gameId;const p=await sb.from("players").select("id,name,phone,email").order("name");const g=await sb.from("games").select("*").order("game_date");const r=await sb.from("game_players").select("*");const fs=await sb.from("finance_seasons").select("id,starts_on,ends_on");const ft=await sb.from("finance_season_tickets").select("id,season_id,player_id,amount,paid,paid_on");if(p.error||g.error||r.error||fs.error||ft.error)throw(p.error||g.error||r.error||fs.error||ft.error);playerFinanceData={seasons:fs.data||[],tickets:ft.data||[]};state.players=(p.data||[]).map(x=>({id:x.id,name:x.name,phone:x.phone||"",email:x.email||""}));state.games=(g.data||[]).map(x=>({id:x.id,date:x.game_date,startTime:String(x.start_time).slice(0,5),endTime:String(x.end_time).slice(0,5),time:String(x.start_time).slice(0,5)+"–"+String(x.end_time).slice(0,5),location:x.location,participants:[]}));const map=new Map(state.games.map(x=>[x.id,x]));(r.data||[]).forEach(x=>{const g=map.get(x.game_id);if(g)g.participants.push({rowId:x.id,playerId:x.player_id,guest:!x.player_id,name:x.guest_name,playing:x.playing,attended:x.attended,paid:x.paid});});if(!state.games.length&&can("games.manage")){state.games=makeSeasonGames();gameId=state.games[0]?.id;await save();}if(!state.games.length){gameId=null;return;}if(!options.resetSelection&&preserveGameId&&state.games.some(x=>x.id===preserveGameId))gameId=preserveGameId;else gameId=state.games.find(x=>x.date>=new Date().toISOString().slice(0,10))?.id||state.games[0]?.id;}
