const KEY="football-castellon-admin-v1";
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const nextFriday=()=>{const d=new Date();const n=(5-d.getDay()+7)%7||7;d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const fmt=d=>new Date(d+"T12:00:00").toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"short",year:"numeric"});
const esc=v=>String(v==null?"":v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",\"":"&quot;"}[c]));
const seed={players:[{id:"p1",name:"João Silva",active:true,payment:"season",seasonPaid:true},{id:"p2",name:"Marco Ruiz",active:true,payment:"game",seasonPaid:false},{id:"p3",name:"David Costa",active:true,payment:"game",seasonPaid:false},{id:"p4",name:"Luis Martín",active:true,payment:"season",seasonPaid:false}],games:[{id:"g1",date:nextFriday(),time:"20:00",location:"Castellón",participants:[{playerId:"p1",playing:true,attended:true,paid:false},{playerId:"p2",playing:true,attended:true,paid:true},{playerId:"p3",playing:true,attended:false,paid:false},{playerId:"p4",playing:false,attended:false,paid:false},{playerId:"guest-demo",guest:true,name:"Carlos",playing:true,attended:true,paid:true}]}]};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||seed,currentView="dashboard",currentGameId=state.games[0]&&state.games[0].id;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const game=()=>state.games.find(g=>g.id===currentGameId);
const player=id=>state.players.find(p=>p.id===id);
const isSeason=x=>!x.guest&&player(x.playerId)&&player(x.playerId).payment==="season";
function render(){document.querySelectorAll(".nav-item").forEach(b=>{b.classList.toggle("active",b.dataset.view===currentView);b.onclick=()=>{currentView=b.dataset.view;render()}});document.getElementById("app").innerHTML=currentView==="dashboard"?dashboard():currentView==="calendar"?calendar():currentView==="players"?players():games();bind()}
function head(title,eyebrow,sub,actions){return "<div class=\"page-head\"><div><div class=\"eyebrow\">"+eyebrow+"</div><div class=\"title\">"+title+"</div><div class=\"muted\">"+sub+"</div></div><div class=\"actions\">"+(actions||"")+"</div></div>"}
function dashboard(){const g=game();if(!g)return head("No Friday yet","Dashboard","Create your first Friday.","<button class=\"btn btn-primary\" data-action=\"new-game\">Create Friday</button>");const playing=g.participants.filter(x=>x.playing).length,present=g.participants.filter(x=>x.attended).length,paid=g.participants.filter(x=>x.attended&&x.paid&&!isSeason(x)).length,tickets=state.players.filter(x=>x.payment==="season"&&x.seasonPaid).length;let html=head(fmt(g.date),"Next Friday",g.time+" · "+g.location,"<button class=\"btn btn-secondary\" data-action=\"add-guest\">+ Guest</button><button class=\"btn btn-primary\" data-action=\"add-player\">+ Player</button>");html+="<div class=\"stats\"><div class=\"card\"><div class=\"stat-label\">Playing</div><div class=\"stat-value\">"+playing+"</div></div><div class=\"card\"><div class=\"stat-label\">Present</div><div class=\"stat-value\">"+present+"</div></div><div class=\"card\"><div class=\"stat-label\">Paid this game</div><div class=\"stat-value\">"+paid+"</div></div><div class=\"card\"><div class=\"stat-label\">Season tickets</div><div class=\"stat-value\">"+tickets+"</div></div></div>";html+="<div class=\"section\"><div class=\"section-head\"><h2>Friday roster</h2><span class=\"muted small\">Per-game payment applies only when present.</span></div><div class=\"table-wrap\"><table class=\"table\"><thead><tr><th>Player</th><th>Type</th><th>Playing</th><th>Present</th><th>Payment</th><th></th></tr></thead><tbody>"+g.participants.map(row).join("")+"</tbody></table></div></div>";return html}
function row(x){const p=x.guest?null:player(x.playerId),name=x.guest?x.name:p?p.name:"Unknown",season=isSeason(x);let payment=season?("<span class=\"badge "+(p.seasonPaid?"badge-green":"badge-red")+"\">"+(p.seasonPaid?"Season paid":"Season unpaid")+"</span>"):x.attended?("<input class=\"check\" type=\"checkbox\" data-toggle=\"paid\" data-part=\""+x.playerId+"\" "+(x.paid?"checked":"")+">"):"<span class=\"muted\">—</span>";return "<tr><td><strong>"+esc(name)+"</strong></td><td><span class=\"badge "+(x.guest?"badge-amber":season?"badge-green":"badge-slate")+"\">"+(x.guest?"Guest":season?"🎟 Season":"Per game")+"</span></td><td><input class=\"check\" type=\"checkbox\" data-toggle=\"playing\" data-part=\""+x.playerId+"\" "+(x.playing?"checked":"")+"></td><td><input class=\"check\" type=\"checkbox\" data-toggle=\"attended\" data-part=\""+x.playerId+"\" "+(x.attended?"checked":"")+"></td><td>"+payment+"</td><td><button class=\"btn btn-secondary small\" data-action=\"remove\" data-part=\""+x.playerId+"\">Remove</button></td></tr>"}
function seasonBadge(p){return "<span class=\"badge "+(p.seasonPaid?"badge-green":"badge-red")+"\">"+(p.seasonPaid?"Paid":"Unpaid")+"</span>"}
function calendar(){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1),start=(first.getDay()+6)%7,last=new Date(year,month+1,0).getDate(),prev=new Date(year,month,0).getDate();let cells="";for(let i=0;i<42;i++){let day=i-start+1,date,muted=false;if(day<1){date=new Date(year,month-1,prev+day)}else if(day>last){date=new Date(year,month+1,day-last);muted=true}else{date=new Date(year,month,day);muted=false}let iso=date.toISOString().slice(0,10),gs=state.games.filter(g=>g.date===iso);cells+="<div class=\"calendar-day "+(muted?"muted-day":"")+"\"><div class=\"day-number\">"+date.getDate()+"</div>"+gs.map(g=>"<div class=\"game-chip\" data-action=\"open-game\" data-id=\""+g.id+"\">⚽ "+esc(g.time||"") +"<small>"+esc(g.location||"")+"</small></div>").join("")+"</div>"}return head(now.toLocaleDateString("en-GB",{month:"long",year:"numeric"}),"Schedule","Fridays and any additional games on the calendar.","<button class=\"btn btn-primary\" data-action=\"new-game\">+ New Friday</button>")+"<div class=\"calendar\"><div class=\"calendar-head\"><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div><div>Sun</div></div><div class=\"calendar-grid\">"+cells+"</div></div>"}
function players(){let rows=state.players.map(p=>"<tr><td><strong>"+esc(p.name)+"</strong></td><td>"+(p.payment==="season"?"Season ticket":"Pay per game")+"</td><td>"+(p.payment==="season"?seasonBadge(p):"—")+"</td><td><span class=\"badge "+(p.active?"badge-green":"badge-slate")+"\">"+(p.active?"Active":"Inactive")+"</span></td><td><button class=\"btn btn-secondary\" data-action=\"edit-player\" data-id=\""+p.id+"\">Edit</button></td></tr>").join("");return head("Players","Roster","Regular players and season-ticket status.","<button class=\"btn btn-primary\" data-action=\"new-player\">+ Add Player</button>")+"<div class=\"table-wrap\"><table class=\"table\"><thead><tr><th>Name</th><th>Payment model</th><th>Season payment</th><th>Status</th><th></th></tr></thead><tbody>"+rows+"</tbody></table></div>"}
function games(){let rows=[...state.games].sort((a,b)=>b.date.localeCompare(a.date)).map(g=>{let pl=g.participants.filter(x=>x.playing).length,pr=g.participants.filter(x=>x.attended).length,pd=g.participants.filter(x=>x.attended&&x.paid&&!isSeason(x)).length;return "<div class=\"card game-card\"><div><div class=\"game-date\">"+fmt(g.date)+"</div><div class=\"muted\">"+esc(g.time)+" · "+esc(g.location)+"</div></div><div class=\"actions\"><span class=\"badge badge-slate\">"+pl+" playing</span><span class=\"badge badge-slate\">"+pr+" present</span><span class=\"badge "+(pd===pr?"badge-green":"badge-amber")+"\">"+pd+"/"+pr+" paid</span><button class=\"btn btn-primary\" data-action=\"open-game\" data-id=\""+g.id+"\">Open</button></div></div>"}).join("");return head("Friday games","History","Each Friday keeps its own attendance and payment records.","<button class=\"btn btn-primary\" data-action=\"new-game\">+ New Friday</button>")+"<div class=\"game-list\">"+rows+"</div>"}
function modal(title,body){document.getElementById("modal-root").innerHTML="<div class=\"modal-bg\" data-close><div class=\"modal\" onclick=\"event.stopPropagation()\"><h2>"+title+"</h2>"+body+"</div></div>"}
function bind(){document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset));document.querySelectorAll("[data-toggle]").forEach(x=>x.onchange=()=>{let p=game().participants.find(y=>y.playerId===x.dataset.part);p[x.dataset.toggle]=x.checked;if(x.dataset.toggle==="attended"&&!x.checked)p.paid=false;save();render()})}
function action(a,d){if(a==="new-game")return modal("New Friday","<form id=\"game-form\"><div class=\"field\"><label>Date</label><input name=\"date\" type=\"date\" value=\""+nextFriday()+"\" required></div><div class=\"field\"><label>Time</label><input name=\"time\" type=\"time\" value=\"20:00\"></div><div class=\"field\"><label>Location</label><input name=\"location\" value=\"Castellón\"></div><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-secondary\" data-close>Cancel</button><button class=\"btn btn-primary\">Create</button></div></form>");
if(a==="new-player"||a==="edit-player"){let p=a==="edit-player"?player(d.id):null;return modal(p?"Edit Player":"Add Player","<form id=\"player-form\" data-id=\""+(p?p.id:"")+""><div class=\"field\"><label>Name</label><input name=\"name\" value=\""+esc(p?p.name:"")+" \" required autofocus></div><div class=\"field\"><label>Payment model</label><select name=\"payment\"><option value=\"game\" "+(p&&p.payment==="game"?"selected":"")+">Pay per game</option><option value=\"season\" "+(p&&p.payment==="season"?"selected":"")+">Season ticket</option></select></div><label class=\"checkbox-row\"><input name=\"seasonPaid\" type=\"checkbox\" "+(p&&p.seasonPaid?"checked":"")+"> Season ticket paid</label><label class=\"checkbox-row\"><input name=\"active\" type=\"checkbox\" "+(!p||p.active?"checked":"")+"> Active player</label><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-secondary\" data-close>Cancel</button><button class=\"btn btn-primary\">Save</button></div></form>")}
if(a==="add-player"){let ids=new Set(game().participants.filter(x=>!x.guest).map(x=>x.playerId)),available=state.players.filter(p=>p.active&&!ids.has(p.id)),opts=available.map(p=>"<option value=\""+p.id+"\">"+esc(p.name)+(p.payment==="season"?" · 🎟 Season":"")+"</option>").join("");return modal("Add Player to Friday","<form id=\"pick-form\"><div class=\"field\"><label>Player</label><select name=\"id\" required>"+opts+"</select></div><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-secondary\" data-close>Cancel</button><button class=\"btn btn-primary\" "+(available.length?"":"disabled")+">Add</button></div></form>")}
if(a==="add-guest")return modal("Add Guest","<form id=\"guest-form\"><div class=\"field\"><label>Guest name</label><input name=\"name\" required autofocus></div><div class=\"notice\">Guest payment is tracked for this Friday only.</div><div class=\"modal-actions\"><button type=\"button\" class=\"btn btn-secondary\" data-close>Cancel</button><button class=\"btn btn-primary\">Add guest</button></div></form>");
if(a==="remove"){game().participants=game().participants.filter(x=>x.playerId!==d.part);save();render()}
if(a==="open-game"){currentGameId=d.id;currentView="dashboard";render()}}
document.addEventListener("click",e=>{if(e.target.closest("[data-close]"))document.getElementById("modal-root").innerHTML=""});
document.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(e.target);if(e.target.id==="game-form"){let g={id:uid(),date:f.get("date"),time:f.get("time"),location:f.get("location"),participants:[]};state.games.push(g);currentGameId=g.id}if(e.target.id==="player-form"){let p=player(e.target.dataset.id);if(!p){p={id:uid(),active:true};state.players.push(p)}p.name=f.get("name").trim();p.payment=f.get("payment");p.seasonPaid=f.has("seasonPaid");p.active=f.has("active")}if(e.target.id==="pick-form")game().participants.push({playerId:f.get("id"),playing:true,attended:false,paid:false});if(e.target.id==="guest-form")game().participants.push({playerId:uid(),guest:true,name:f.get("name").trim(),playing:true,attended:false,paid:false});save();document.getElementById("modal-root").innerHTML="";render()});
document.getElementById("newGame").onclick=()=>action("new-game");render();