-- Football Castellón
-- MySQL/MariaDB target schema for the PHP migration.
-- Target: MariaDB 11.x / PHP 8.4
-- IDs are generated by the PHP application as UUID strings.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS access_profiles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS team_captain_history;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS finance_expenses;
DROP TABLE IF EXISTS finance_season_tickets;
DROP TABLE IF EXISTS finance_seasons;
DROP TABLE IF EXISTS game_players;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS players;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE players (
    id CHAR(36) NOT NULL,
    name VARCHAR(160) NOT NULL,
    phone VARCHAR(64) NULL,
    email VARCHAR(254) NULL,
    skill_level TINYINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY players_archived_at_idx (archived_at),
    KEY players_email_idx (email),
    CONSTRAINT players_skill_level_chk CHECK (skill_level IS NULL OR skill_level BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE games (
    id CHAR(36) NOT NULL,
    game_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    location VARCHAR(255) NOT NULL DEFAULT 'Castellón',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY games_date_time_idx (game_date, start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE game_players (
    id CHAR(36) NOT NULL,
    game_id CHAR(36) NOT NULL,
    player_id CHAR(36) NULL,
    guest_name VARCHAR(160) NULL,
    playing BOOLEAN NOT NULL DEFAULT FALSE,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    took_bibs BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY game_players_game_id_idx (game_id),
    KEY game_players_player_id_idx (player_id),
    CONSTRAINT game_players_game_fk FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT game_players_player_fk FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE SET NULL,
    CONSTRAINT game_players_identity_chk CHECK (player_id IS NOT NULL OR guest_name IS NOT NULL),
    CONSTRAINT game_players_guest_chk CHECK (player_id IS NULL OR guest_name IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- MariaDB does not support PostgreSQL partial unique indexes. The PHP API
-- enforces the one-bib-taker-per-game rule transactionally.

CREATE TABLE finance_seasons (
    id CHAR(36) NOT NULL,
    name VARCHAR(120) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    season_ticket_price DECIMAL(10,2) NULL,
    game_price DECIMAL(10,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY finance_seasons_name_key (name),
    KEY finance_seasons_dates_idx (starts_on, ends_on),
    CONSTRAINT finance_seasons_dates_chk CHECK (ends_on >= starts_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE finance_season_tickets (
    id CHAR(36) NOT NULL,
    season_id CHAR(36) NOT NULL,
    player_id CHAR(36) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    paid_on DATE NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY finance_season_tickets_season_player_key (season_id, player_id),
    KEY finance_season_tickets_player_idx (player_id),
    CONSTRAINT finance_season_tickets_season_fk FOREIGN KEY (season_id) REFERENCES finance_seasons(id) ON DELETE CASCADE,
    CONSTRAINT finance_season_tickets_player_fk FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
    id CHAR(36) NOT NULL,
    player_id CHAR(36) NOT NULL,
    game_id CHAR(36) NULL,
    payment_type ENUM('game','season') NOT NULL DEFAULT 'game',
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    amount DECIMAL(10,2) NULL,
    paid_on DATE NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY payments_game_id_idx (game_id),
    KEY payments_player_id_idx (player_id),
    CONSTRAINT payments_player_fk FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT payments_game_fk FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE finance_expenses (
    id CHAR(36) NOT NULL,
    expense_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    category VARCHAR(100) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY finance_expenses_date_idx (expense_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE team_captain_history (
    id CHAR(36) NOT NULL,
    game_id CHAR(36) NOT NULL,
    team_name VARCHAR(80) NOT NULL,
    player_id CHAR(36) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY team_captain_history_game_team_key (game_id, team_name),
    KEY idx_team_captain_history_player (player_id),
    CONSTRAINT team_captain_history_game_fk FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT team_captain_history_player_fk FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Authentication is deliberately separate from access_profiles. A user may
-- authenticate with Google before an administrator links that account to a
-- football player/access profile.
CREATE TABLE users (
    id CHAR(36) NOT NULL,
    google_subject VARCHAR(255) NULL,
    email VARCHAR(254) NOT NULL,
    display_name VARCHAR(160) NULL,
    avatar_path VARCHAR(500) NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY users_google_subject_key (google_subject),
    UNIQUE KEY users_email_key (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Access registry. This intentionally supports rows with user_id NULL so an
-- administrator can pre-authorise an email before the first Google login.
CREATE TABLE access_profiles (
    email VARCHAR(254) NOT NULL,
    user_id CHAR(36) NULL,
    player_id CHAR(36) NULL,
    role ENUM('super_admin','admin','attendance','finance','viewer','player') NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    avatar_path VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (email),
    UNIQUE KEY access_profiles_user_id_key (user_id),
    UNIQUE KEY access_profiles_player_id_key (player_id),
    KEY access_profiles_role_idx (role),
    CONSTRAINT access_profiles_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT access_profiles_player_fk FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE role_permissions (
    role ENUM('super_admin','admin','attendance','finance','viewer','player') NOT NULL,
    permission VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (role, permission)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE sessions (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY sessions_token_hash_key (token_hash),
    KEY sessions_user_idx (user_id),
    KEY sessions_expires_idx (expires_at),
    CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default permission matrix. This mirrors the permissions exposed by the
-- current application. Super Admin is handled as an implicit full-access role
-- by the PHP authorization layer.
INSERT INTO role_permissions (role, permission, enabled) VALUES
('admin','dashboard.view',TRUE),
('admin','players.view',TRUE),
('admin','players.manage',TRUE),
('admin','games.view',TRUE),
('admin','games.manage',TRUE),
('admin','attendance.view',TRUE),
('admin','attendance.manage',TRUE),
('admin','payments.view',TRUE),
('admin','payments.manage',TRUE),
('admin','access.manage',TRUE),
('attendance','dashboard.view',TRUE),
('attendance','players.view',TRUE),
('attendance','players.manage',TRUE),
('attendance','games.view',TRUE),
('attendance','games.manage',TRUE),
('attendance','attendance.view',TRUE),
('attendance','attendance.manage',TRUE),
('finance','dashboard.view',TRUE),
('finance','players.view',TRUE),
('finance','games.view',TRUE),
('finance','attendance.view',TRUE),
('finance','payments.view',TRUE),
('finance','payments.manage',TRUE),
('viewer','dashboard.view',TRUE),
('viewer','players.view',TRUE),
('viewer','games.view',TRUE),
('viewer','attendance.view',TRUE),
('player','games.view',TRUE),
('player','dashboard.view',FALSE),
('player','players.view',FALSE),
('player','players.manage',FALSE),
('player','games.manage',FALSE),
('player','attendance.view',FALSE),
('player','attendance.manage',FALSE),
('player','payments.view',FALSE),
('player','payments.manage',FALSE),
('player','access.manage',FALSE)
ON DUPLICATE KEY UPDATE enabled = VALUES(enabled);

SET FOREIGN_KEY_CHECKS = 1;
